AWSTemplateFormatVersion: 2010-09-09
Description : Basic EC2 Instance.


Parameters:
  MyKeyname:
    Description: Select the key from the list
    Type: AWS::EC2::KeyPair::KeyName
  
  MyAvailabilityZone:
    Description: Select the AZ
    Type : String
    Default: us-east-2a
    AllowedValues:
      - us-east-2a
      - us-east-2b

  MyInstanceType:
    Description : Select EC2 instance type from
    Type : String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small


Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-027cab9a7bf0155df
      InstanceType: !Ref MyInstanceType
      KeyName : !Ref MyKeyname
      SecurityGroups:
        - default
        - !Ref SSHSecurityGroup
      AvailabilityZone: !Ref MyAvailabilityZone
  
  
  SSHSecurityGroup:
    Type : AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: my new SSH SG
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: 0.0.0.0/0
      
